name: black-action
on:
  push: {}
  pull_request:
    types: [reopened]
jobs:
  format_code:
    name: runner / black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Check files using the black formatter
        uses: rickstaa/action-black@v1
        id: action_black
        with:
          black_args: "."
          fail_on_error: "true"
      - name: Commit changes
        if: steps.action_black.outputs.is_formatted == 'true'
        run: |
          git config --global user.name 'black-formatter'
          git config --global user.email 'black-formatter@github.com'
          git commit -am "Committing format changes"
          git push
