name: build base image
on:
  workflow_dispatch: {}
  push:
    branches:
      - "main"
    paths:
      - "requirements.txt"
env:
  AWS_REGION: "us-west-2"
  ECR_REPOSITORY: "backend"
  IMAGE_PREFIX: "base"
  ACCOUNT_ID: "872291417442"
jobs:
  Buildbaseimage:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout
    steps:
      - name: Get current date
        run: |
          echo "CURRENT_TIME=$(date +'%Y-%m-%dT%H-%M-%S')" >> $GITHUB_ENV
      - name: Get branch name
        run: echo "BRANCH=${GITHUB_REF_NAME//\//-}" >> $GITHUB_ENV
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ env.ACCOUNT_ID }}:role/GithubActionCICD
          role-session-name: cicdrolesession
          aws-region: ${{ env.AWS_REGION }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ env.IMAGE_PREFIX }}_${{ env.BRANCH }}-${{ env.CURRENT_TIME }}
        run: |
          docker build -f ./deployments/Dockerfile-base -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: "Backend base image updated"
# TODO: add a step to update BASE_IMAGE_TAG in .github/workflows/deploy-backend-*.yml
