name: onboarding customer

on:
  workflow_dispatch: {}

jobs:
  job1:
    uses: ./.github/workflows/update-customer-info.yml@main
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{ needs.job1.outputs.org_name }}