name: Sync GraphQL Schema
on:
  push:
    branches:
      - "main"
    paths:
      - "src/formacloud/gql/schema.graphql"
      - "src/formacloud/gql/schema.admin.graphql"
env:
  AWS_REGION: "us-west-2"
  ACCOUNT_ID: "872291417442"
jobs:
  sync-graphql-schema:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ env.ACCOUNT_ID }}:role/GithubActionCICD
          role-session-name: cicdrolesession
          aws-region: ${{ env.AWS_REGION }}
      - name: Copy schema files to S3
        run: |
          touch graphql-schema.lock
          aws s3 cp graphql-schema.lock s3://formacloud-graphql-schema/graphql-schema.lock
          aws s3 cp src/formacloud/gql s3://formacloud-graphql-schema/ --recursive --exclude "*" --include "*.graphql"
          aws s3 rm s3://formacloud-graphql-schema/graphql-schema.lock
