name: update customer info

on:
  workflow_dispatch:
    inputs:
      org_name:
        description: "Organization name"
      billing_account_id:
        description: "Billing account ID"
      external_id_autopilot:
        description: "External ID for Autopilot"
      external_id_saving_bot:
        description: "External ID for SavingBot"

jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
        - name: Get Time
          id: time
          uses: nanzm/get-time-action@master
          with:
            format: "YYYY-MM-DD-HH-mm-ss"
        - name: Checkout repo
          uses: actions/checkout@v4
        - name: Update Customer Info
          run: echo "| ${{ github.event.inputs.org_name }} | | ${{ github.event.inputs.billing_account_id }} | ${{ github.event.inputs.external_id_autopilot }} | | - Autopilot-v1.5| us-west-2 |||" >> assets/data/CustomerInfo.md
        - name: Create PR
          env:
            BRANCH_NAME: update-customer-${{ steps.time.outputs.time }}
            GH_TOKEN: ${{ github.token }}
          run: |
            git config --global user.email CustomerInfoUpdater@auto.onboarding
            git config --global user.name customer-info-updater
            git checkout -b "$BRANCH_NAME"
            git add .
            if [[ "$(git status --porcelain|wc -l)" -gt 0 ]]; then
              git commit --message "Update Customer Info"
              git push -u origin HEAD:$BRANCH_NAME
              gh pr create --base main --head $BRANCH_NAME --title "Update Customer Info" --body "Update customer info. If this PRs got merged, the auto-onboarding workflow would get started."
            fi
