name: update customer info

on:
  workflow_dispatch:
    inputs:
      org_name:
        description: "Organization name"
      billing_account_id:
        description: "Billing account ID"
      external_id_autopilot:
        description: "External ID for Autopilot"
      external_id_saving_bot:
        description: "External ID for SavingBot"

jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
        - name: Hello Step
          run: |
            pwd