name: Update customer info
on:
  workflow_dispatch:
    inputs:
      org_name:
        description: "Organization name"
      billing_account_id:
        description: "Billing account ID"
      external_id_autopilot:
        description: "External ID for Autopilot"
      external_id_saving_bot:
        description: "External ID for SavingBot"
      autopilot_version:
        description: "Autopilot version"
env:
  AWS_REGION: "us-west-2"
  ACCOUNT_ID: "872291417442"
  ECR_REPOSITORY: "backend"
  ORG_NAME: ${{ github.event.inputs.org_name }}
  BILLING_ACCOUNT_ID: ${{ github.event.inputs.billing_account_id }}
  EXTERNAL_ID_AUTOPILOT: ${{ github.event.inputs.external_id_autopilot }}
  EXTERNAL_ID_SAVING_BOT: ${{ github.event.inputs.external_id_saving_bot }}
  AUTOPILOT_VERSION: ${{ github.event.inputs.autopilot_version }}
jobs:
  # update-customer-info:
  #   runs-on: ubuntu-latest
  #   permissions:
  #     id-token: write # This is required for requesting the JWT
  #     contents: write # This is required for actions/checkout & creating pull requests
  #     pull-requests: write # This is required for creating pull requests
  #   steps:
  #   - name: Checkout repo
  #     uses: actions/checkout@v4
  #   - name: Update Customer Info
  #     run: echo "| ${ORG_NAME} | | ${BILLING_ACCOUNT_ID} | ${EXTERNAL_ID_AUTOPILOT} | ${EXTERNAL_ID_SAVING_BOT} | ${AUTOPILOT_VERSION} ||||" >> assets/data/CustomerInfo.md
  #   - name: Get Time
  #     id: time
  #     uses: nanzm/get-time-action@master
  #     with:
  #       format: "YYYY-MM-DD-HH-mm-ss"
  #   - name: Create PR
  #     env:
  #       BRANCH_NAME: update-customer-${{ env.ORG_NAME }}-${{ steps.time.outputs.time }}
  #       GH_TOKEN: ${{ github.token }}
  #     run: |
  #       git config --global user.email CustomerInfoUpdater@auto.onboarding
  #       git config --global user.name customer-info-updater
  #       git checkout -b "${BRANCH_NAME}"
  #       git add .
  #       if [[ "$(git status --porcelain|wc -l)" -gt 0 ]]; then
  #         git commit --message "update customer info ${ORG_NAME}"
  #         git push -u origin HEAD:${BRANCH_NAME}
  #         gh pr create --base main --head ${BRANCH_NAME} --title "Update customer info for ${ORG_NAME}" --body "Update customer info for ${ORG_NAME}. It will be synced to Slab."
  #       fi
  onboarding-customer:
    runs-on: ubuntu-latest
    # environment: onboarding customer  # Review required
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Onboarding customer
      run: echo "Onboarding Customer ${ORG_NAME}"
  job2:
    uses: zhang35/test-bash-jiaqi/.github/workflows/onboarding-customer.yml@main