name: update customer info

on:
  workflow_dispatch:
    inputs:
      org_name:
        description: "Organization name"
      billing_account_id:
        description: "Billing account ID"
      external_id_autopilot:
        description: "External ID for Autopilot"
      external_id_saving_bot:
        description: "External ID for SavingBot"

jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repo
          uses: actions/checkout@v4
        - name: Hello Step
          run: |
            echo "| ${{ github.event.inputs.org_name }} | | ${{ github.event.inputs.billing_account_id }} | ${{ github.event.inputs.external_id_autopilot }} | | - Autopilot-v1.5| us-west-2 |||" >> assets/data/CustomerInfo.md
            tail assets/data/CustomerInfo.md